name = "wizevaxel/picguin"
version = "0.0.0"
private = true
license = "MIT"
authors = ["wizeväxel"]
repository = "https://github.com/wizevaxel/picguin"

workspace_members = ["packages/*"]

[target]
environment = "luau"

[indices]
default = "https://github.com/pesde-pkg/index"
