name = "literallywize/picguin"
version = "0.0.0"
private = true
license = "MIT"
authors = ["LiterallyWize"]
repository = "https://github.com/LiterallyWize/picguin"

workspace_members = ["packages/*"]

[target]
environment = "luau"
