name = "picguin/png"
version = "0.1.0"
authors = ["LiterallyWize"]
repository = "https://github.com/LiterallyWize/picguin"
license = "MIT"
includes = ["src/**/*", "pesde.toml"]

[target]
environment = "roblox"
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }

[dependencies]
core = { workspace = "picguin/core", version = "^"  }
