name: Release Codec

on:
  workflow_dispatch:
    inputs:
      codec:
        type: choice
        required: true
        options:
          - png

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.2.1

      - name: Setup pesde
        uses: pesde-pkg/setup@v1
        with:
          token: ${{ secrets.PESDE_TOKEN }}

      - name: Setup pesde workspace
        run: pesde install

      - name: Build and release
        run: lune run scripts/release ${{ inputs.codec }}

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ env.RELEASE_TAG }}" "release/${{ inputs.codec }}.rbxm" --title "${{ env.RELEASE_TAG }}" --draft
