name: Test Codecs

on:
  push:
    branches: [main]
    paths:
      - 'packages/**'
  pull_request:
    paths:
      - 'packages/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.2.1

      - name: Run tests
        run: zune run scripts/tests
